using System;
using System.Collections.Generic;
using System.Text;
using Xunit;
using SortingAlgorithms.Models;

namespace Tests.UnitTests
{
    public class MergeSortTests
    {
        [Fact]
        public void TestMergeSort()
        {
            // arrange
            int[] unsortedArray = new int[5] { 3, 2, 6, 3, 7 };

            // act
            var actual = MergeSort.Sort(unsortedArray);
            int[] expected = new int[5] { 2, 3, 3, 6, 7 };

            // assert
            Assert.Equal(expected, actual);
        }

        [Fact]
        public void TestMergeSortAutoGeneratedArray()
        {
            // arrange
            int[] unsortedArray = GenerateUnsortedArray.GenerateArray(100000);
            int[] unsortedArrayCopy = unsortedArray;
            Array.Sort(unsortedArrayCopy);

            // act
            var actual = MergeSort.Sort(unsortedArray);

            // assert
            Assert.Equal(unsortedArrayCopy, actual);
        }
    }
}
